# Generated by Django 3.1.2 on 2020-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='match',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
