# Generated by Django 3.1.2 on 2020-11-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.CharField(default='Cali', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
