# Generated by Django 3.1.2 on 2020-11-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='tourist',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='author',
            new_name='tour_guide',
        ),
    ]
