# Generated by Django 3.1.2 on 2020-11-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20201105_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='trip',
            new_name='tripId',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='tourist',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tour_guide',
            new_name='userId',
        ),
    ]
