# Generated by Django 3.1.2 on 2020-11-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20201105_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tripId',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='userId',
            new_name='user',
        ),
    ]
