# Generated by Django 3.1.2 on 2020-11-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201105_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourguide',
            old_name='user',
            new_name='userId',
        ),
    ]
